import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import LoadingLogo from "@/components/shared/LoadingLogo";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/ui/theme/theme-provider";
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const viewport: Viewport = {
  themeColor: "DodgerBlue",
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next-Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            <ClerkLoading>
              <LoadingLogo />
            </ClerkLoading>
            <ClerkLoaded>
              <TooltipProvider>{children}</TooltipProvider>
              <Toaster richColors />
            </ClerkLoaded>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
